// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    // Test name: test1
    // Step # | name | target | value
    // 1 | open | https://sakshingp.github.io/assignment/login.html# | 
    driver.get("https://sakshingp.github.io/assignment/login.html#");
    // 2 | setWindowSize | 1296x688 | 
    driver.manage().window().setSize(new Dimension(1296, 688));
    // 3 | click | id=username | 
    driver.findElement(By.id("username")).click();
    // 4 | type | id=username | sscmukul@gmail.com
    driver.findElement(By.id("username")).sendKeys("sscmukul@gmail.com");
    // 5 | click | id=password | 
    driver.findElement(By.id("password")).click();
    // 6 | type | id=password | simanshu
    driver.findElement(By.id("password")).sendKeys("simanshu");
    // 7 | click | id=log-in | 
    driver.findElement(By.id("log-in")).click();
    // 8 | click | css=.selected span | 
    driver.findElement(By.cssSelector(".selected span")).click();
    // 9 | click | css=.os-icon-chevron-down | 
    driver.findElement(By.cssSelector(".os-icon-chevron-down")).click();
    // 10 | click | css=.autosuggest-search-activator > input | 
    driver.findElement(By.cssSelector(".autosuggest-search-activator > input")).click();
    // 11 | type | css=.autosuggest-search-activator > input | qwdjkn
    driver.findElement(By.cssSelector(".autosuggest-search-activator > input")).sendKeys("qwdjkn");
    // 12 | sendKeys | css=.autosuggest-search-activator > input | ${KEY_ENTER}
    driver.findElement(By.cssSelector(".autosuggest-search-activator > input")).sendKeys(Keys.ENTER);
  }
}
